[package]
name = "deepseek-cli-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
deepseek-api = { git = "https://github.com/meanwhile131/deepseek-api-rs.git", version = "0.1.0" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.1"
